---
actions_toolbox:
  pingonly:
    - test
  doinventory:
    - inventory
  deploy:
    - copyfile

actions_vars:
  pingonly: []
  doinventory:
    - toolbox.inventory
  deploy:
    - toolbox.deploy

actions_excluded:
  - pingonly
