---
- name: Create inventory
  hosts: localhost
  connection: local
  gather_facts: false

  pre_tasks:

    - name: Set global fact for base dir
      set_fact:
        play_dir: "{{ playbook_dir | dirname }}"

    - name: Include pre-tasks
      include_tasks: "{{ play_dir }}/pretasks.yml"
      vars:
        assert_vars:
          - filename

  tasks:

    - name: Create inventory
      include_role:
        name: toolbox
      vars:
        toolbox:
          inventory: "{{ common.raspi.inventory | default() }}"
        action_toolbox: doinventory

- name: Run {{ doaction | default('pingonly') }} on Linux
  hosts: linuxadhoc
  gather_facts: false

  tasks:

    - name: Running {{ doaction | default('pingonly') }} toolbox
      include_role:
        name: toolbox
      vars:
        toolbox:
          deploy:
            name: "{{ filename | default() }}"
            destination: "{{ hostvars.localhost.common.raspi.deploy.destdir | default() }}"
        action_toolbox: "{{ doaction | default('pingonly') }}"
